/*--------------------------------------------------------------------------------------------------
EDA 
---------------------------------------------------------------------------------------------------*/

-- Explore all objects in database.

SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='dim_customers'

-- Dimensions Exploration 

-- Explore all countries our customers come from

SELECT DISTINCT country FROM gold.dim_customers;

-- Explore all categories 'The Major Division'

SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products;

-- Date Exploration 

-- Find the date of the first and last order
-- How many years of sales is avialable 
SELECT 
MIN(order_date) first_order_date,
MAX(order_date) last_order_date,
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) as order_range_years
FROM gold.fact_sales;

-- Find the youngest and oldest customer 

SELECT 
MIN(birthdate) as oldest_birthdate,
MAX(birthdate) as youngest_birthdate
FROM gold.dim_customers


-- Measure Exploration 

-- Find total customers by countries

SELECT
country,
COUNT(DISTINCT customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC 

SELECT * FROM gold.dim_customers

-- Find total customers by gender

SELECT 
gender,
COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers  DESC

-- Find total products by category 

SELECT 
category,
COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category

SELECT
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category 

SELECT 
p.category,
SUM(f.sales_amount) AS revenue 
FROM gold.fact_sales f 
INNER JOIN gOLD.dim_products P
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY revenue DESC


-- Find total revenue generated by each customer 

SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS  toal_revenue 
FROM gold.fact_sales f
INNER JOIN gold.dim_customers c
ON c.customer_key =  f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY toal_revenue DESC

-- What is the distribution of sold items accross all countries 

SELECT 
c.country,
SUM(f.quantity) AS  sold_items 
FROM gold.fact_sales f
INNER JOIN gold.dim_customers c
ON c.customer_key =  f.customer_key
GROUP BY c.country 
ORDER BY sold_items DESC


-- Ranking : 

-- which 5 prducts generate the highest revenue 


SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS revenue 
FROM gold.fact_sales f 
INNER JOIN gold.dim_products P
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY revenue DESC


SELECT 
p.product_name,
SUM(f.sales_amount) AS revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount)DESC) AS rank_products
FROM gold.fact_sales f 
INNER JOIN gold.dim_products P
ON p.product_key = f.product_key
GROUP BY p.product_name


-- Which are the 5 worst performing-products in terms of sales?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS revenue 
FROM gold.fact_sales f 
INNER JOIN gold.dim_products P
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY revenue 


-- Top 10 customers who have generated the highest revenue 

SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS  toal_revenue 
FROM gold.fact_sales f
INNER JOIN gold.dim_customers c
ON c.customer_key =  f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY toal_revenue DESC


-- The 3 customers with fewer orders placed

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS  toal_orders 
FROM gold.fact_sales f
INNER JOIN gold.dim_customers c
ON c.customer_key =  f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY toal_orders 